apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::518115029107:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QLTUQAFA3NVC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::518115029107:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T01:18:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "243938"
  uid: b4965b35-5abc-44c9-bda0-d3baf792a873
